export const DEFAULT_INPUT_DATA_AGE_ID = 1;
export const DEFAULT_EXECUTION_GROUP_ORDER_ID = 1;
export const DEFAULT_HIGH_LEVEL_SYSTEM_OR_MODEL_ID = 0;
export const DEFAULT_HARDWARE_MODEL_ID = 0;
export const HARDWARE_INTERFACE_TYPE_NOT_APPLICABLE = 0;
export const DEFAULT_HARDWARE_INTERFACE_TYPE_ID = HARDWARE_INTERFACE_TYPE_NOT_APPLICABLE;
export const MODEL_SOURCE_SDS_GENERIC_MODEL = 2;
export const MODEL_SOURCE_SIMULINK_MODEL = 3;
export const DEFAULT_MODEL_SOURCE_ID = MODEL_SOURCE_SDS_GENERIC_MODEL;

export {};
